global using gateway_resonance_pass.Application.Interfaces;
global using gateway_resonance_pass.Domain.ValueObjects;
global using gateway_resonance_pass.Infraestructure.Repositories;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Newtonsoft.Json;
global using System.Text;
global using Flurl.Http;
global using gateway_resonance_pass.Domain.Entities;
global using gateway_resonance_pass.Domain.Exceptions;
global using gateway_resonance_pass.Application.Decimatio.Queries.Comunas.Get;
global using gateway_resonance_pass.Application.Decimatio.Queries.Eventos.GetAll;
global using gateway_resonance_pass.Application.Decimatio.Queries.Eventos.GetById;
global using gateway_resonance_pass.Application.Decimatio.Queries.Eventos.GetFilter;
global using gateway_resonance_pass.Application.Decimatio.Queries.Eventos.GetPage;
global using gateway_resonance_pass.Application.Decimatio.Queries.MediosPagos.Get;
global using gateway_resonance_pass.Application.Decimatio.Queries.MediosPagos.GetById;
global using gateway_resonance_pass.Application.Decimatio.Queries.TipoUsuarios.Get;

